sharedemail.settings:
  type: config_object
  label: 'Shared Email settings'
  mapping:
    sharedemail_msg:
      type: text
      label: 'Default warning message for Shared Email:'
    sharedemail_allowed:
      type: string
      label: 'Whitelisted email addresses for Shared Email:'
